name: mkdocs-deploy
run-name: ${{ github.actor }} is deploying gpac mkdocs wiki
on: workflow_dispatch
jobs:
  build-mkdocs:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get submodules
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.GH_WIKI_DEPLOY_KEY}}"; git submodule update --init --recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: install mkdocs-material
        run: pip install mkdocs-material 
        # run: pip install mkdocs-material=="9.5.6" 
      - name: build mkdocs
        run: mkdocs build --clean -d ./site
      - name: disable SEO indexing
        run: | 
          echo " 
          User-agent: *
          Disallow: /
          " > ./site/robots.txt 
      - name: files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{vars.WIKI_FTP_HOST}}
          username: ${{secrets.WIKI_FTP_USER}}
          password: ${{secrets.WIKI_FTP_PASS}}
          local-dir: ./site/
          server-dir: www/
          state-file: .sync-state.json
          exclude: |
            **/.git*
            **/.git*/**
            .ftpquota
            */**.htaccess
            .check_spell.sh
            .well-known*/**
